# Generated by Django 3.1.7 on 2021-03-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(default='temp', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
