# Generated by Django 3.1.7 on 2021-03-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210308_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('slug', 'store')},
        ),
    ]
