# Generated by Django 3.1.7 on 2021-03-10 00:39

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210309_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='title')),
                ('slug', models.SlugField(max_length=100)),
                ('body', models.TextField(verbose_name='body')),
                ('image', models.ImageField(blank=True, upload_to=core.models.collection_image_file_path)),
                ('type', models.CharField(choices=[('ALL', 'All conditions'), ('ANY', 'Any conditions')], default='ALL', max_length=9, verbose_name='Collection Type')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_reference', models.CharField(choices=[('TYPE', 'Product Type'), ('TITLE', 'Product Title'), ('VENDOR', 'Product Vendor'), ('TAG', 'Product Tag'), ('STOCK', 'Product Stock'), ('PRICE', 'Product Price')], default='TYPE', max_length=25, verbose_name='Field Reference')),
                ('filter_type', models.CharField(choices=[('EQUAL', 'Is equal to'), ('NOTEQUAL', 'Not equal to'), ('GREATERTHANEQUAL', 'Greater than'), ('LESSTHANEQUAL', 'Less than'), ('STARTSWITH', 'Starts with'), ('ENDSWITH', 'Ends with'), ('CONTAINS', 'Contains'), ('NOTCONTAIN', 'Does not contain')], default='EQUAL', max_length=25, verbose_name='Filter Type')),
                ('field_val', models.CharField(max_length=35, verbose_name='Condition Value')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collection')),
            ],
        ),
    ]
