# Generated by Django 3.1.7 on 2021-03-16 03:17

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_collection_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('AND', 'All conditions'), ('OR', 'Any conditions')], default='AND', max_length=9, verbose_name='Collection Type'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='field_reference',
            field=models.CharField(choices=[('TYPE', 'Product Type'), ('TITLE', 'Product Title'), ('TAG', 'Product Tag'), ('STOCK', 'Product Stock'), ('PRICE', 'Product Price')], default='TYPE', max_length=25, verbose_name='Field Reference'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='rating')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('review', models.TextField(verbose_name='Description')),
                ('was_helpful', models.IntegerField(verbose_name='Helpful')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('image', models.ImageField(upload_to=core.models.upload_path_handler, verbose_name='Image')),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('file', models.FileField(upload_to=core.models.upload_path_handler, verbose_name='File')),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
