# Generated by Django 3.1.7 on 2021-03-17 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210316_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattachment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_active',
        ),
    ]
