# Generated by Django 3.1.7 on 2021-03-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210317_2127'),
    ]

    operations = [
    ]
