# Generated by Django 3.1.7 on 2021-03-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210324_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finished_at',
            field=models.DateTimeField(null=True, verbose_name='Finalized'),
        ),
    ]
