# Generated by Django 3.1.7 on 2021-03-29 16:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210329_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='invalid_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 16, 25, 51, 283514, tzinfo=utc), verbose_name='Invalid'),
        ),
    ]
