# Generated by Django 3.1.7 on 2021-03-29 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210329_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='invalid_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 19, 32, 30, 462825, tzinfo=utc), verbose_name='Invalid'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
